-- AlterTable
ALTER TABLE "infrastruktur" ADD COLUMN "fotoCropX" DOUBLE PRECISION DEFAULT 50;
ALTER TABLE "infrastruktur" ADD COLUMN "fotoCropY" DOUBLE PRECISION DEFAULT 50;
ALTER TABLE "infrastruktur" ADD COLUMN "fotoCropZoom" DOUBLE PRECISION DEFAULT 1;
